version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: pashim/dockerex:1.0.2
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
    - "8081:80"
    networks:
    - webnet
networks:
  webnet: